baseURL = "https://Aknowd.github.io/"
languageCode = "ja"
#title = "Self-Assembly Laboratory"
theme = "labtheme"

paginate = 10

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

[params.homeInfo]
title = "K's Portfolio"
content = """
"""

[[params.homeInfo.buttons]]
name = "研究ノート"
url = "/posts/"

[[params.homeInfo.buttons]]
name = "Project D.A.S.Q."
url = "/dasq/"

[[params.homeInfo.buttons]]
name = "GitHub"
url = "https://github.com/<yourname>"


[params.assets]
customCSS = ["css/custom.css"]
hero = "/images/who.png"


[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Diary"
  url = "/diary/"
  weight = 2

  [[menu.main]]
  name = "Tools"
  url = "/tools/"
  weight = 3

  [[menu.main]]
  name = "Papers"
  url = "/papers/"
  weight = 4

  [[menu.main]]
  name = "Relax"
  url = "/relax/"
  weight = 5

  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 6


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[outputs]
home = ["HTML"]
section = ["HTML", "JSON"]

[outputFormats.JSON]
mediaType = "application/json"
baseName = "index"
isPlainText = true

ignoreConfig = ["themes/labtheme/hugo.toml"]